config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/pages/:origin/:currencies', to: 'pages#index', defaults: { origin: 'BRL', currencies: 'EUR,USD,AUD,BRL' }, as: :converter

  get '/', to: redirect('/pages/BRL/EUR,USD,AUD,BRL'), as: :main
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @currencies        = params[:currencies].split(',')
    @origin            = params[:origin]
    @target_currencies = (@currencies - [@origin])

    @data = CurrencyReporter.new(origin: @origin, targets: @target_currencies).report

  rescue StandardError => e
    flash[:error] = e.message
    redirect_to main_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartmailCodeExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="https://github.com/Nerian/code_example_smart_mail" target="_blank">See code on Github</a>
        </li>
      </ul>

      <span class="navbar-text"><a href="http://nerian.es/" target="_blank">Made by Gonzalo Rodríguez-Baltanás Díaz</a></span>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.slim
.card#super-graph
  .card-header
    <ul class="nav nav-pills card-header-pills">
      - @currencies.each do |target|
        li
          - if @origin == target
            = link_to @origin, converter_path(origin: @origin), class: 'nav-link active'
          - else
            = link_to target, converter_path(origin: target), class: 'nav-link'

  .card-body
    p
      <b>1 #{Money::Currency.new(@origin).name}</b> exchange rate to <b>#{@target_currencies.join(', ')}</b>

    - if flash[:error]
      .alert.alert-danger
        = flash[:error]

    = line_chart @data, { legend: "bottom", points: false }